### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lawiter** [jdhao/deep_firearm#1]
FileNotFoundError: [Error 2] No such file or directory: '/···/deep_firearm/deepfirearm-master/libs/cls_train_data.pt'

**Comment by jdhao** [comment]
Can you print the full error message? Are you running the code as directed by the documentation?

**Comment by lawiter** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/amax/deep_firearm/deep_firearm-master/libs/cls_train_data.pt'

**Comment by jdhao** [comment]
You should set `regen_train_test=True`  when you first train the classification model. Also, there are some path errors in the code when `regen_train_test=False`, I will fix this error when I have time.

**Comment by jdhao** [comment]
@lawiter , the error has been fixed.
