### ISSUE TITLE
Unable to access Dataset link

### ISSUE THREAD

**Issue by pjspillai** [jdhao/deep_firearm#2]
Hi, I am unable to download dataset from the provided link. Is it active?

[http://forensics.idealtest.org/Firearm14k/](http://forensics.idealtest.org/Firearm14k)/

**Comment by jdhao** [comment]
@pjspillai  It seems that this link is deal now. I will find if I can upload the dataset to other cloud storage. Stay tuned!

**Comment by pjspillai** [comment]
Hi jdhao, any luck uploading the dataset links?

**Comment by jdhao** [comment]
@pjspillai  Sorry for keeping you waiting so long. The dataset link has been updated.  See  commit https://github.com/jdhao/deep_firearm/commit/46fa4671236c2ae3fb09820f374e254f4bd9f32b.
